name: okk
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "TeamUltroid/Ultroid"
          replace: "MR-UNKNOWN-X/testing"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'there was a conflict'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: MR-UNKNOWN-X
          commit_user_email: vikrantkumar3499@gmail.com
          commit_author: MR-UNKNOWN-X <vikrantkumar3499@gmail.com
